CREATE TABLE USUARIO (
    UsuCod INT AUTO_INCREMENT PRIMARY KEY,
    UsuNom VARCHAR(80),
    UsuCor VARCHAR(130) UNIQUE NOT NULL,
    UsuCon VARCHAR(130),
    UsuFecReg DATE,
    UsuEstReg CHAR(1)
);
CREATE TABLE ROL (
    RolCod INT AUTO_INCREMENT PRIMARY KEY,
    RolNom VARCHAR(40) UNIQUE NOT NULL,
    RolDes VARCHAR(160),
    RolEstReg CHAR(1)
);
CREATE TABLE PLAGA (
    PlaCod INT AUTO_INCREMENT PRIMARY KEY,
    PlaNom VARCHAR(80) UNIQUE NOT NULL,
    PlaDes VARCHAR(160),
    PlaTip VARCHAR(40),
    PlaGra VARCHAR(40),
    PlaEstReg CHAR(1)
);
CREATE TABLE MODELO (
    ModCod INT AUTO_INCREMENT PRIMARY KEY,
    ModNom VARCHAR(40) NOT NULL,
    ModVer DECIMAL,
    ModFecEnt DATE,
    ModTipMod VARCHAR(40) UNIQUE,
    ModEstReg CHAR(1)
);
CREATE TABLE ZONA_GEOGRAFICA (
    ZonCod INT AUTO_INCREMENT PRIMARY KEY,
    ZonNom VARCHAR(80) UNIQUE NOT NULL,
    ZonTipZon VARCHAR(40),
    ZonReg VARCHAR(80),
    ZonEstReg CHAR(1)
);
CREATE TABLE IMAGEN (
    ImaCod INT AUTO_INCREMENT PRIMARY KEY,
    ImaUrl VARCHAR(130) UNIQUE NOT NULL,
    ImaTam INT,
    ImaRes VARCHAR(40),
    ImaFecCap DATE,
    ImaPro VARCHAR(40),
    ImaTipIma VARCHAR(40),
    ImaEstReg CHAR(1)
);
CREATE TABLE ALERTA (
    AleCod INT AUTO_INCREMENT PRIMARY KEY,
    AleTip VARCHAR(40) NOT NULL,
    AleMen VARCHAR(160),
    AleGra VARCHAR(40),
    AleFecGen DATE,
    AleEstReg CHAR(1)
);
CREATE TABLE MENSAJE_CHAT (
    MenCod INT AUTO_INCREMENT PRIMARY KEY,
    MenUsuCod INT,
    MenUsuBCod INT,
    MenCon VARCHAR(160) NOT NULL,
    MenFecHor DATE,
    MenEstReg CHAR(1),
    FOREIGN KEY (MenUsuBCod) REFERENCES USUARIO(UsuCod)
);
CREATE TABLE DATOS_OFFLINE_BUFFER (
    DatCod INT AUTO_INCREMENT PRIMARY KEY,
    DatUsuCod INT,
    DatTipDat VARCHAR(40),
    DatCon VARCHAR(160) NOT NULL,
    DatFecCre DATE,
    DatSin VARCHAR(40),
    DatEstReg CHAR(1),
    FOREIGN KEY (DatUsuCod) REFERENCES USUARIO(UsuCod)
);
CREATE TABLE SYNC_LOG (
    SynCod INT AUTO_INCREMENT PRIMARY KEY,
    SynUsuCod INT,
    SynFec DATE NOT NULL,
    SynTipSin VARCHAR(40),
    SynRes VARCHAR(40),
    SynEstReg CHAR(1),
    FOREIGN KEY (SynUsuCod) REFERENCES USUARIO(UsuCod)
);
CREATE TABLE USUARIO_ROL (
    UsuCod INT AUTO_INCREMENT PRIMARY KEY,
    UsuUsuCod INT,
    UsuRolCod INT,
    UsuEstReg CHAR(1),
    FOREIGN KEY (UsuUsuCod) REFERENCES USUARIO(UsuCod),
    FOREIGN KEY (UsuRolCod) REFERENCES ROL(RolCod)
);
CREATE TABLE RECOMENDACION (
    RecCod INT AUTO_INCREMENT PRIMARY KEY,
    RecPlaCod INT,
    RecNomCul VARCHAR(80) NOT NULL,
    RecNivDañ DECIMAL,
    RecAccSug VARCHAR(160) NOT NULL,
    RecEstReg CHAR(1),
    FOREIGN KEY (RecPlaCod) REFERENCES PLAGA(PlaCod)
);
CREATE TABLE MAPA_PARCELA (
    MapCod INT AUTO_INCREMENT PRIMARY KEY,
    MapUsuCod INT,
    MapZonGeoCod INT,
    MapImaMap VARCHAR(130) UNIQUE,
    MapAnc INT NOT NULL,
    MapAlt INT NOT NULL,
    MapFecSub DATE,
    MapNom VARCHAR(80) NOT NULL,
    MapCom VARCHAR(160),
    MapEstReg CHAR(1),
    FOREIGN KEY (MapUsuCod) REFERENCES USUARIO(UsuCod),
    FOREIGN KEY (MapZonGeoCod) REFERENCES ZONA_GEOGRAFICA(ZonCod)
);
CREATE TABLE ESTADISTICA_AGREGADA (
    EstCod INT AUTO_INCREMENT PRIMARY KEY,
    EstFec DATE NOT NULL,
    EstZonGeoCod INT,
    EstNomCul VARCHAR(80) NOT NULL,
    EstPlaCod INT,
    EstTotCas INT,
    EstMedDañ DECIMAL,
    EstEstReg CHAR(1),
    FOREIGN KEY (EstPlaCod) REFERENCES PLAGA(PlaCod),
    FOREIGN KEY (EstZonGeoCod) REFERENCES ZONA_GEOGRAFICA(ZonCod)
);
CREATE TABLE CLIMA (
    CliCod INT AUTO_INCREMENT PRIMARY KEY,
    CliFec DATE NOT NULL,
    CliZonGeoCod INT,
    CliTem DECIMAL,
    CliHum DECIMAL,
    CliLlu DECIMAL,
    CliFue VARCHAR(40),
    CliEstReg CHAR(1),
    FOREIGN KEY (CliZonGeoCod) REFERENCES ZONA_GEOGRAFICA(ZonCod)
);
CREATE TABLE PREDICCION (
    PreCod INT AUTO_INCREMENT PRIMARY KEY,
    PrePlaCod INT,
    PreZonGeoCod INT,
    PreFecEst DATE NOT NULL,
    PrePro DECIMAL,
    PreModCod INT,
    PreEstReg CHAR(1),
    FOREIGN KEY (PrePlaCod) REFERENCES PLAGA(PlaCod),
    FOREIGN KEY (PreModCod) REFERENCES MODELO(ModCod),
    FOREIGN KEY (PreZonGeoCod) REFERENCES ZONA_GEOGRAFICA(ZonCod)
);
CREATE TABLE USUARIO_ALERTA (
    UsuCod INT AUTO_INCREMENT PRIMARY KEY,
    UsuUsuCod INT,
    UsuAleCod INT,
    UsuLei VARCHAR(40),
    UsuFecLec DATE,
    UsuEstReg CHAR(1),
    FOREIGN KEY (UsuUsuCod) REFERENCES USUARIO(UsuCod),
    FOREIGN KEY (UsuAleCod) REFERENCES ALERTA(AleCod)
);
CREATE TABLE CULTIVO_PARCELA (
    CulCod INT AUTO_INCREMENT PRIMARY KEY,
    CulMapParCod INT,
    CulNomCul VARCHAR(80) NOT NULL,
    CulFecIni DATE,
    CulFecFin DATE,
    CulObs VARCHAR(160),
    CulEstReg CHAR(1),
    FOREIGN KEY (CulMapParCod) REFERENCES MAPA_PARCELA(MapCod)
);
CREATE TABLE ACCESO_PARCELA (
    AccCod INT AUTO_INCREMENT PRIMARY KEY,
    AccUsuCod INT,
    AccMapParCod INT,
    AccRolAcc VARCHAR(40),
    AccPer VARCHAR(160),
    AccFecAsi DATE NOT NULL,
    AccEstReg CHAR(1),
    FOREIGN KEY (AccMapParCod) REFERENCES MAPA_PARCELA(MapCod),
    FOREIGN KEY (AccUsuCod) REFERENCES USUARIO(UsuCod)
);
CREATE TABLE UBICACION (
    UbiCod INT AUTO_INCREMENT PRIMARY KEY,
    UbiMapParCod INT,
    UbiCoo DECIMAL,
    UbiCooB DECIMAL,
    UbiCom VARCHAR(160),
    UbiEstReg CHAR(1),
    FOREIGN KEY (UbiMapParCod) REFERENCES MAPA_PARCELA(MapCod)
);
CREATE TABLE CAPTURA (
    CapCod INT AUTO_INCREMENT PRIMARY KEY,
    CapUsuCod INT,
    CapImaCod INT,
    CapUbiCod INT,
    CapFec DATE NOT NULL,
    CapNot VARCHAR(160),
    CapEstReg CHAR(1),
    FOREIGN KEY (CapUbiCod) REFERENCES UBICACION(UbiCod),
    FOREIGN KEY (CapUsuCod) REFERENCES USUARIO(UsuCod),
    FOREIGN KEY (CapImaCod) REFERENCES IMAGEN(ImaCod)
);
CREATE TABLE DIAGNOSTICO (
    DiaCod INT AUTO_INCREMENT PRIMARY KEY,
    DiaCapCod INT,
    DiaPlaCod INT,
    DiaNivDañ DECIMAL,
    DiaCon DECIMAL NOT NULL,
    DiaModCod INT,
    DiaFec DATE,
    DiaEstReg CHAR(1),
    FOREIGN KEY (DiaPlaCod) REFERENCES PLAGA(PlaCod),
    FOREIGN KEY (DiaModCod) REFERENCES MODELO(ModCod),
    FOREIGN KEY (DiaCapCod) REFERENCES CAPTURA(CapCod)
);
CREATE TABLE ETIQUETA_MANUAL (
    EtiCod INT AUTO_INCREMENT PRIMARY KEY,
    EtiDiaCod INT,
    EtiUsuCod INT,
    EtiPlaCor VARCHAR(80),
    EtiObs VARCHAR(160) NOT NULL,
    EtiFec DATE,
    EtiEstReg CHAR(1),
    FOREIGN KEY (EtiDiaCod) REFERENCES DIAGNOSTICO(DiaCod),
    FOREIGN KEY (EtiUsuCod) REFERENCES USUARIO(UsuCod)
);

